{{- $configmap:= .Values.configmap_data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- toYaml $configmap.data | nindent 2 }}
