{{- $app:= .Values.hello -}}
{{- $configmap:= .Values.configmap_data -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: {{ $app.container_port }}
  selector:
    app: {{ $app.name }}-app
