{{- $app:= .Values.hello -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $app.name }}-app
  template:
    metadata:
      labels:
        app: {{ $app.name }}-app
    spec:
      containers:
        - name: {{ $app.name }}-app
          image: {{ $app.image }}
          env:
          {{- range $key, $val := $app.env }}
            - name: {{ $val.name | quote }}
              value: {{ $val.value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $app.container_port }}
