{{- $teamcity_server:= .Values.teamcity.server -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $teamcity_server.name }}-storage
  namespace: {{ .Values.namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
